# Generated by Django 3.0.2 on 2020-04-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblrl', '0003_auto_20200418_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='friend',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
